name: surya_dhegde
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - jupyter_contrib_nbextensions
  - wandb
  - numba
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - sunpy
  - xarray
  - dask
  - bottleneck
  - h5netcdf
  - hdf5plugin
  - opencv
  - pyarrow=23.*
  - pip
  - pip:
    - torch
    - torchvision
    - lightning
    - peft
    - torchmetrics
    - s3fs==2024.6.1
    - einops
    - huggingface_hub
    - datasets==2.21.0
    - fsspec==2024.6.1
    - hf_transfer
    - timm
    - boto3==1.41.5
